### ISSUE TITLE
how to train with custom dataset? 

### ISSUE THREAD

**Issue by marziyemahmoudifar** [zhaohengyuan1/Color2Style#4]
Hi,
I want to train this code with my own dataset.
How can I give my dataset as input to the network?

**Comment by zhaohengyuan1** [comment]
Dear Marziye,

If you want to use your dataset, I recommend you to edit the codes of dir
https://github.com/zhaohengyuan1/Color2Embed/blob/main/data/prepare_data.py.

**Comment by marziyemahmoudifar** [comment]
I edited the data path in the prepare_data.py file, but I got this error (FileNotFoundError: Found no valid file for the classes labels. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp) and I don't know what the label is. Can you tell me what the label is? I have encountered this error for a long time and it cannot be solved.

**Comment by zhaohengyuan1** [comment]
You could follow the indication of error information to check the correctness of the path you gave.

**Comment by marziyemahmoudifar** [comment]
I gave my own dataset as input to the prepare_data.py, but it gives this error. How should I define the class?
Make dataset of image sizes: 256
Traceback (most recent call last):
  File "prepare_data.py", line 81, in <module>
    imgset = datasets.ImageFolder(args.path)
  File "/home/gadmin/yolov5/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 310, in __init__
    super(ImageFolder, self).__init__(root, loader, IMG_EXTENSIONS if is_valid_file is None else None,
  File "/home/gadmin/yolov5/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/gadmin/yolov5/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/home/gadmin/yolov5/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in ../train/apple.

**Comment by AsserOssama** [comment]
@marziyemahmoudifar did u solve the problem??

**Comment by zhaohengyuan1** [comment]
Yes, I did.

Asser Ossama ***@***.***> 于2023年5月19日周五 06:24写道：

**Comment by AsserOssama** [comment]
how ??

**Comment by AsserOssama** [comment]
and can u give me dataset structure or sample from it?
